version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/twg2022
hooks:
  BeforeInstall:
    - location: stopapache_beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: startapache_applicationstart.sh
      timeout: 300
      runas: root
